# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_input',
            field=models.BinaryField(default=b''),
        ),
    ]
