# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-20 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180120_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='test_input',
        ),
    ]
