# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-20 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180120_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Question'),
        ),
        migrations.AddField(
            model_name='room',
            name='round_duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='room',
            name='round_start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='total_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.Room'),
        ),
    ]
