# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-21 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20180120_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='question',
        ),
        migrations.RemoveField(
            model_name='room',
            name='round_duration',
        ),
        migrations.RemoveField(
            model_name='room',
            name='round_start_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='total_duration',
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit_seconds',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=4),
        ),
    ]
