# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-21 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20180120_2256'),
        ('chat', '0008_auto_20180121_0223'),
    ]

    operations = [
    ]
