# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-21 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=3),
        ),
    ]
